name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    env:
      DB_CONNECTION: sqlite
      DB_DATABASE: ./database/database.sqlite
      APP_ENV: testing

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, bcmath, pdo, pdo_sqlite
          coverage: none

      - name: Install system deps
        run: sudo apt-get update -y && sudo apt-get install -y git unzip

      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Prepare environment file for CI (SQLite)
        run: cp .env.ci .env

      - name: Create sqlite database file
        run: |
          mkdir -p database
          touch database/database.sqlite
          chmod -R 0777 database || true

      - name: Generate minimal phpunit.xml for CI
        run: |
          cat > phpunit.xml <<'PHPUNIT'
          <?xml version="1.0" encoding="UTF-8"?>
          <phpunit bootstrap="vendor/autoload.php" colors="true">
            <testsuites>
              <testsuite name="Feature">
                <directory suffix="Test.php">./tests/Feature</directory>
              </testsuite>
              <testsuite name="Unit">
                <directory suffix="Test.php">./tests/Unit</directory>
              </testsuite>
            </testsuites>
            <php>
              <env name="APP_ENV" value="testing"/>
              <env name="DB_CONNECTION" value="sqlite"/>
              <env name="DB_DATABASE" value="./database/database.sqlite"/>
            </php>
          </phpunit>
          PHPUNIT
          chmod 0644 phpunit.xml
          echo "phpunit.xml created."

      - name: Generate app key & clear caches
        run: |
          php artisan key:generate --ansi
          php artisan config:clear
          php artisan cache:clear

      - name: Run migrations (sqlite)
        run: php artisan migrate --force --no-interaction

      - name: Run tests
        run: php artisan test --verbose
