name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, bcmath, pdo, pdo_sqlite
          coverage: none

      - name: Install system deps (composer needs)
        run: sudo apt-get update -y && sudo apt-get install -y git unzip

      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Prepare environment file for CI (SQLite)
        run: cp .env.ci .env

      - name: Create sqlite database file
        run: |
          mkdir -p database
          touch database/database.sqlite
          chmod -R 0777 database || true

      - name: Generate application key & clear config
        run: |
          php artisan key:generate --ansi
          php artisan config:clear

      - name: Run migrations (uses sqlite file)
        run: php artisan migrate --force

      - name: Run tests
        run: php artisan test --verbose
